---
name: PR Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: fmt and validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2
        with:
          terraform_version: 1.14.0

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Prepare unit test providers
        run: cp tests/unit/setup/providers.tf providers.tf

      - name: Terraform init
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
